// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {update} from '../models';

export function AddProject(arg1:string):Promise<domain.DiscoveryResult>;

export function ApplicationName():Promise<string>;

export function CheckForUpdates():Promise<update.Info>;

export function CopySkill(arg1:string,arg2:string):Promise<domain.DiscoveryResult>;

export function DeleteSkill(arg1:string):Promise<domain.DiscoveryResult>;

export function DiscoverLocalEnvironment():Promise<domain.DiscoveryResult>;

export function DownloadAndInstallUpdate(arg1:string):Promise<void>;

export function InstallSkillFromURL(arg1:string,arg2:string):Promise<domain.SkillInstallResult>;

export function RemoveProject(arg1:string):Promise<domain.DiscoveryResult>;

export function SelectProjectFolder():Promise<string>;

export function SetSkillInvocationMode(arg1:string,arg2:string):Promise<domain.DiscoveryResult>;
