// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddProject(arg1) {
  return window['go']['main']['App']['AddProject'](arg1);
}

export function ApplicationName() {
  return window['go']['main']['App']['ApplicationName']();
}

export function CopySkill(arg1, arg2) {
  return window['go']['main']['App']['CopySkill'](arg1, arg2);
}

export function DeleteSkill(arg1) {
  return window['go']['main']['App']['DeleteSkill'](arg1);
}

export function DiscoverLocalEnvironment() {
  return window['go']['main']['App']['DiscoverLocalEnvironment']();
}

export function InstallSkillFromURL(arg1, arg2) {
  return window['go']['main']['App']['InstallSkillFromURL'](arg1, arg2);
}

export function RemoveProject(arg1) {
  return window['go']['main']['App']['RemoveProject'](arg1);
}

export function SelectProjectFolder() {
  return window['go']['main']['App']['SelectProjectFolder']();
}
